Use C99 mode for rebar.config
Because the following error occurred:

    $ make build
    ...
    ==> eroonga (compile)
    Compiling c_src/eroonga.c
    c_src/eroonga.c: In function ‘table_select’:
    c_src/eroonga.c:177:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i = 0; i < n; i++) {
             ^
    c_src/eroonga.c:177:9: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
    ERROR: compile failed while processing /.../eroonga: rebar_abort
    Makefile:49: recipe for target 'build' failed
    make: *** [build] Error 1